//! Platform-neutral description of what the user is doing.
//!
//! These types live in the core crate rather than the hook crate so the engine
//! can be exercised end to end in tests, with no keyboard and no OS involved.

/// A keystroke as the hook sees it.
#[derive(Debug, Clone, PartialEq)]
pub struct KeyEvent {
    /// The character produced, if the key produced one.
    pub character: Option<char>,
    pub key: Key,
    pub modifiers: Modifiers,
    /// True when the event was generated by software — usually by Rekey
    /// itself. Acting on these would make the app respond to its own typing.
    pub synthetic: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Key {
    Character,
    Backspace,
    Space,
    Enter,
    Tab,
    Escape,
    /// Arrows, Home/End, PageUp/Down — anything that moves the caret.
    Navigation,
    /// A modifier was pressed or released and nothing else happened. Tapping
    /// one is how the manual "cycle the last word" shortcut is triggered.
    ModifiersChanged,
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Modifiers {
    pub shift: bool,
    pub control: bool,
    pub alt: bool,
    /// Command on macOS, Windows key on Windows.
    pub meta: bool,
}

impl Modifiers {
    /// True when this looks like a shortcut rather than typing. Shift and the
    /// AltGr-style Alt are excluded because both are used to produce ordinary
    /// characters on many layouts.
    pub fn is_shortcut(self) -> bool {
        self.control || self.meta
    }
}

/// What the OS says is currently happening, sampled when a word ends.
#[derive(Debug, Clone, Default)]
pub struct Context {
    /// Bundle id on macOS, executable name on Windows.
    pub app: Option<String>,
    /// The active keyboard layout, as a Rekey layout id.
    pub layout: Option<String>,
    /// macOS secure input, or a Windows password field: never type here.
    pub secure_input: bool,
}

/// Puts corrected text into whatever the user is typing in.
///
/// Implemented by each platform's injector, and by a recording fake in tests.
pub trait TextWriter: Send + Sync {
    /// Delete `count` characters behind the caret.
    fn backspace(&self, count: usize);
    /// Type `text` as if the user had.
    fn type_text(&self, text: &str);

    /// Type by replaying physical key presses, given as `(key index, shift)`.
    ///
    /// This is the reliable way to produce text. Attaching a Unicode string to
    /// a synthetic event is only a request, and many applications ignore it and
    /// re-derive the character from the key code instead — which yields the
    /// same wrong letter repeated, because every such event carries the same
    /// key code. Replaying the presses with the matching layout selected is
    /// indistinguishable from typing.
    ///
    /// Returns false if the platform cannot do this, so the caller can fall
    /// back to [`TextWriter::type_text`].
    fn type_keys(&self, _presses: &[crate::layout::KeyPress]) -> bool {
        false
    }

    /// Replace the last `delete` characters with `text`.
    fn replace(&self, delete: usize, text: &str) {
        if delete > 0 {
            self.backspace(delete);
        }
        if !text.is_empty() {
            self.type_text(text);
        }
    }
}
